import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class LgdService {
  private directory = {
    fields: [
      {
        id: 'a',
        label: '﻿"state_code"',
        type: 'string',
      },
      {
        id: 'b',
        label: 'state_name_english',
        type: 'string',
      },
      {
        id: 'c',
        label: 'state_name_local',
        type: 'string',
      },
      {
        id: 'd',
        label: 'state_census2011_code',
        type: 'string',
      },
      {
        id: 'e',
        label: 'state_or_ut',
        type: 'string',
      },
      {
        id: 'f',
        label: 'last_updated',
        type: 'string',
      },
    ],
    data: [
      [
        35,
        'Andaman And Nicobar Islands',
        'ANDAMAN AND NICOBAR ISLANDS                       ',
        35,
        'U',
        '2023-08-01',
      ],
      [
        28,
        'Andhra Pradesh',
        'ANDHRA PRADESH                                    ',
        28,
        'S',
        '2023-08-01',
      ],
      [
        12,
        'Arunachal Pradesh',
        'ARUNACHAL PRADESH                                 ',
        12,
        'S',
        '2023-08-01',
      ],
      [
        18,
        'Assam',
        'ASSAM                                             ',
        18,
        'S',
        '2023-08-01',
      ],
      [
        10,
        'Bihar',
        'BIHAR                                             ',
        10,
        'S',
        '2023-08-01',
      ],
      [
        4,
        'Chandigarh',
        'CHANDIGARH                                        ',
        '04',
        'U',
        '2023-08-01',
      ],
      [22, 'Chhattisgarh', 'छत्तीसगढ़', 22, 'S', '2023-08-01'],
      [
        7,
        'Delhi',
        'DELHI                                             ',
        '07',
        'U',
        '2023-08-01',
      ],
      [
        30,
        'Goa',
        'GOA                                               ',
        30,
        'S',
        '2023-08-01',
      ],
      [
        24,
        'Gujarat',
        'GUJARAT                                           ',
        24,
        'S',
        '2023-08-01',
      ],
      [
        6,
        'Haryana',
        'HARYANA                                           ',
        '06',
        'S',
        '2023-08-01',
      ],
      [
        2,
        'Himachal Pradesh',
        'HIMACHAL PRADESH                                  ',
        '02',
        'S',
        '2023-08-01',
      ],
      [1, 'Jammu And Kashmir', 'JAMMU AND KASHMIR', '01', 'U', '2023-08-01'],
      [20, 'Jharkhand', 'झारखंड', 20, 'S', '2023-08-01'],
      [29, 'Karnataka', 'ಕರ್ನಾಟಕ', 29, 'S', '2023-08-01'],
      [
        32,
        'Kerala',
        'KERALA                                            ',
        32,
        'S',
        '2023-08-01',
      ],
      [37, 'Ladakh', 'NA', '00', 'U', '2023-08-01'],
      [
        31,
        'Lakshadweep',
        'LAKSHADWEEP                                       ',
        31,
        'U',
        '2023-08-01',
      ],
      [
        23,
        'Madhya Pradesh',
        'MADHYA PRADESH                                    ',
        23,
        'S',
        '2023-08-01',
      ],
      [27, 'Maharashtra', 'महाराष्ट्र', 27, 'S', '2023-08-01'],
      [
        14,
        'Manipur',
        'MANIPUR                                           ',
        14,
        'S',
        '2023-08-01',
      ],
      [
        17,
        'Meghalaya',
        'MEGHALAYA                                         ',
        17,
        'S',
        '2023-08-01',
      ],
      [
        15,
        'Mizoram',
        'MIZORAM                                           ',
        15,
        'S',
        '2023-08-01',
      ],
      [
        13,
        'Nagaland',
        'NAGALAND                                          ',
        13,
        'S',
        '2023-08-01',
      ],
      [21, 'Odisha', 'ODISHA', 21, 'S', '2023-08-01'],
      [34, 'Puducherry', 'PUDUCHERRY', 34, 'U', '2023-08-01'],
      [
        3,
        'Punjab',
        'PUNJAB                                            ',
        '03',
        'S',
        '2023-08-01',
      ],
      [
        8,
        'Rajasthan',
        'RAJASTHAN                                         ',
        '08',
        'S',
        '2023-08-01',
      ],
      [
        11,
        'Sikkim',
        'SIKKIM                                            ',
        11,
        'S',
        '2023-08-01',
      ],
      [
        33,
        'Tamil Nadu',
        'TAMIL NADU                                        ',
        33,
        'S',
        '2023-08-01',
      ],
      [36, 'Telangana', 'తెలంగాణ', '00', 'S', '2023-08-01'],
      [
        38,
        'The Dadra And Nagar Haveli And Daman And Diu',
        'THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU',
        'NA',
        'U',
        '2023-08-01',
      ],
      [16, 'Tripura', 'ত্রিপুরা', 16, 'S', '2023-08-01'],
      [5, 'Uttarakhand', 'UTTARAKHAND', '05', 'S', '2023-08-01'],
      [
        9,
        'Uttar Pradesh',
        'UTTAR PRADESH                                     ',
        '09',
        'S',
        '2023-08-01',
      ],
    ],
  };
  constructor() {}

  getStates() {
    return this.directory.data;
  }
}
